[Ready for Review] French - Design and Develop Overview
w3c/wai-design-develop-overview pull request #10
Opened 2020-10-19 19:57 UTC by Soahmed2031

2021-03-16 00:16 UTC, remibetin requested changes
Thank you @Soahmed2031 for your work on this french translation. Here is my review with suggestions and thoughts.

I also noticed in the Netlify preview that some links to non-translated resources are not displayed with "(en anglais)" at the end, but I don't know why it is sometimes automatically added and sometimes not.

Let me know what you think of my input.

2021-03-16 00:16 UTC, remibetin commented on index.fr.md
> +: Une référence personnalisable aux exigences (“critères de réussite”) et aux techniques des Règles de l’accessibilité des contenus Web (WCAG).
The meaning is not very easy to grasp. "Référence rapide" seems to be used in Canada and Switzerland, but is really used in France.  Suggestion "Un aide-mémoire personnalisable des exigences ("critères de réussite") et des techniques [...]"

2021-03-16 00:16 UTC, remibetin commented on index.fr.md
> +[Comment répondre aux exigences des WCAG (référence rapide)](https://www.w3.org/WAI/WCAG21/quickref/)
What do you think of "aide-mémoire" rather than "référence rapide" ? (see comment below)

2021-03-16 00:16 UTC, remibetin commented on index.fr.md
> +[Pratiques de création WAI-ARIA](https://www.w3.org/TR/wai-aria-practices/)
"Pratiques de création **de** WAI-ARIA" ? (sous-entendu création d'applications accessibles)

2021-03-16 00:16 UTC, remibetin commented on index.fr.md
> +: Fournit des approches, des conseils, et des exemples pour aider les développeurs d’applications Web à créer des widgets, une navigation, et des comportements accessibles en utilisant les rôles, les
Maybe we should use `<i>` around _Accessible Rich Internet Applications_ considering it is in a foreign langage.

2021-03-26 00:32 UTC, slhenry commented
integrated into https://github.com/w3c/wai-design-develop-overview/pull/11

2021-03-26 00:32 UTC, closed without merging